### ISSUE TITLE
Opener does not display state correctly at "Dauerbetrieb"

### ISSUE THREAD

**Issue by senger1985** [Zefau/ioBroker.nuki-extended#30]
When I activate the continuous operation he shows the states below.

in the app but "Ring to open" is displayed
![nuki](https://user-images.githubusercontent.com/35745035/67083523-9693bc00-f19b-11e9-9349-fb8ed341fa3a.PNG)

**Comment by senger1985** [comment]
Damn... 
It is too early, please close the issue.
The states are correctly

**Comment by Zefau** [comment]
Please change to nuki-extended Adapter. You structure looks like nuki2 to me?

**Comment by Zefau** [comment]
See https://forum.iobroker.net/post/313064

**Comment by senger1985** [comment]
Sorry, I have sent the wrong states.
I already have the nuki-extended adapter installed and in use.
I will test and report the developer version asap.

**Comment by Zefau** [comment]
@senger1985 have you had the chance to look at the latest version `rc.7`? Please deleted the state `_ACTION` and restart the adapter, because the state have had an incorrect setting. Thanks.

**Comment by senger1985** [comment]
Here are the states by the latest version rc.7 by activated "Continuous operation"
![nuki](https://user-images.githubusercontent.com/35745035/67241283-6fffaa80-f453-11e9-8eee-82414a6c3e4b.PNG)

**Comment by senger1985** [comment]
@Zefau I've tested the adapter for a few days now.
The states of the smart lock work great.
But I can't find useful objects for the opener.
Which state shows me, whether "Ring to open" has been activated, for example?
"_Action" always stays on "NO_ACTION (0)".

**Comment by Zefau** [comment]
Please try again the v2.0.0.

**Comment by Zefau** [comment]
`_ACTION` is only to trigger actions and will not show any state. This apparently did not work in the recent versions.

**Comment by senger1985** [comment]
after I installed the v2.0.0 I did not get any connection anymore.

nuki-extended.0 2019-10-24 23: 36: 07.403 error (17701) ReferenceError: bridge_ident is not defined at adapter.config.bridges.map (/opt/iobroker/node_modules/iobroker.nuki-extended/nuki-extended .js: 289: 68) at Array.map (<anonymous>) at
nuki-extended.0 2019-10-24 23: 36: 07.402 error (17701) uncaught exception: bridge_ident is not defined

I didn't change the data in the adapter configuration.

**Comment by senger1985** [comment]
I completely uninstalled the adapter today and re-installed it.
But still get the same error as the issue yesterday
Do you have any information, what the problem is?

**Comment by Zefau** [comment]
v2.0.1 should fix that. My bad.

**Comment by senger1985** [comment]
I have now updated to v2.0.1 but I still can not find a state for the opener.
And now also the state "lockState" is missing if the Smart Lock is locked.

**Comment by Zefau** [comment]
`can not find a state for the opener` means you do not have an opener in the tree `nuki-extended.0.openers.<yourOpener>` ?

And the state `lockState` simply does not exist within the tree `nuki-extended.0.openers.<yourSmartlock>.state.lockState` ?

This is very weird. Can you confirm this behavior with the version v2.0.2 as well?
Could you please provide the logs from the adapter startup?

Thanks for your support!

**Comment by senger1985** [comment]
For sure:


nuki-extended.0 | 2019-10-31 10:08:05.005 | warn | (10006) Callback not attached due to error. See debug log for details.
-- | -- | -- | --
nuki-extended.0 | 2019-10-31 10:08:04.245 | info | (10006) Listening for Nuki events on port 51989.
nuki-extended.0 | 2019-10-31 10:08:04.244 | info | (10006) Polling Nuki Web API with a frequency of 30s.
nuki-extended.0 | 2019-10-31 10:08:03.799 | warn | (10006) Failed retrieving /list from Nuki Bridge with name Bridge!
nuki-extended.0 | 2019-10-31 10:06:33.529 | info | (10006) starting. Version 2.0.2 in /opt/iobroker/node_modules/iobroker.nuki-extended, node: v10.16.3
host.senger1985 | 2019-10-31 10:06:30.418 | info | instance system.adapter.nuki-extended.0 started with pid 10006
host.senger1985 | 2019-10-31 10:06:30.379 | info | "system.adapter.nuki-extended.0" enabled

**Comment by Zefau** [comment]
Could you change your instance to `debug` and provide the extended log? Thanks!

**Comment by senger1985** [comment]
No further information at debug-mode available

nuki-extended.0 | 2019-10-31 10:31:21.017 | info | (6136) starting. Version 2.0.2 in /opt/iobroker/node_modules/iobroker.nuki-extended, node: v10.16.3
-- | -- | -- | --
host.senger1985 | 2019-10-31 10:31:18.448 | info | instance system.adapter.nuki-extended.0 started with pid 6136
host.senger1985 | 2019-10-31 10:31:18.409 | info | "system.adapter.nuki-extended.0" enabled

**Comment by Zefau** [comment]
The adapter is not able to connect to your bridge (`Error: socket hang up`).

Are you able to call your bridge manually using your browser by opening `http://192.168.178.xx:8080/list?token=token` ?

**Comment by senger1985** [comment]
Yes, I can do it.

**Comment by senger1985** [comment]
I do not know why.
But in the JSON that is returned to me, no lockstate is available:

[{"deviceType": 0, "nukiId": xxx, "name": "Wohnungstür", "lastKnownState": {"mode": 2, "state": 1, "stateName": "locked", "batteryCritical": false, "timestamp": "2019-10-31T01:20:22+00:00"}}, {"deviceType": 2, "nukiId": xxx, "name": "Haustür", "lastKnownState": {"mode": 2, "state": 1, "stateName": "online", "batteryCritical": false, "timestamp": "2019-10-30T20:34:14+00:00"}}]

**Comment by Zefau** [comment]
The `lockState` is `state`. The adapter is remapping it to separate it from `doorState`

**Comment by Zefau** [comment]
Could you try and install the current version from Github (version number remains unchanged) ?

**Comment by Zefau** [comment]
Thanks for your patience and help in this.

**Comment by senger1985** [comment]
Perfect "lockState" is available again.
You can close the issue.

**Comment by senger1985** [comment]
You are amazing

**Comment by Zefau** [comment]
Does your Nuki Opener shows the correct state though in regards to ring to open?
And does v2.0.2 apply the action correctly to your Nuki Opener (e.g. open the door)?

**Comment by senger1985** [comment]
Only "lastaction" changes from ACTIVE RTO (1) [ringtoopen is activated] to DEACTIVE RTO (2) [ringtoopen is deactivated]
Is that the correct behavior?

**Comment by senger1985** [comment]
"ringToOpenTimer" changes too when activated

**Comment by Zefau** [comment]
Did you do that with the adapter or in the smartphone app?

Correct behavior would be:
1. Triggering the state `_ACTION` should apply the selected action on the Nuki Opener, e.g. `ELECTRIC STRIKE ACTUATION` should open the door.
2. `state.lastAction` simply shows the last applied action from any device (adapter or smartphone app) applied to Nuki Opener
3. `state.lockState` should show `RING_TO_OPEN` when either RTO geo fence is active OR continuous mode is activated.

**Comment by senger1985** [comment]
I do that with in the app.
state.lockState shows ONLINE(1)
_ACTION shows only NO_ACTION(0)

**Comment by senger1985** [comment]
My bad.
STRIKE ACTUATION is displayed when opening

**Comment by Zefau** [comment]
>  _ACTION shows only NO_ACTION(0)
That is true. It will always show that. This is the state you can use to trigger any action. When selected, the state will jump back to `NO_ACTION(0)` but trigger the selected action.

Sounds to me though, that everything works fine? :)

**Comment by senger1985** [comment]
I think so, too ;)
Thank you for the gread adapter

**Comment by Zefau** [comment]
You're very welcome
