### ISSUE TITLE
V2.0.0 error 

### ISSUE THREAD

**Issue by Ilovegym66** [Zefau/ioBroker.nuki-extended#35]
Hi, last version rc-7 works fine, but now with 2.0.0 from this morning I get this error and the adapter stop working. Workaround is to let out the Portnumber of the bridge, than is working... (but only with api not with the bridge..)

`

nuki-extended.0 | 2019-10-25 13:53:51.497 | info | (28447) terminating
-- | -- | -- | --
nuki-extended.0 | 2019-10-25 13:53:51.076 | info | (28447) Terminated (NO_ERROR): Without reason
nuki-extended.0 | 2019-10-25 13:53:51.076 | info | (28447) terminating
nuki-extended.0 | 2019-10-25 13:53:50.992 | info | (28447) Adapter stopped und unloaded.
nuki-extended.0 | 2019-10-25 13:53:50.991 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
nuki-extended.0 | 2019-10-25 13:53:50.991 | error | at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
nuki-extended.0 | 2019-10-25 13:53:50.991 | error | at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
nuki-extended.0 | 2019-10-25 13:53:50.991 | error | at client.mget (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:488:13)
nuki-extended.0 | 2019-10-25 13:53:50.991 | error | at states.getStates (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5587:17)
nuki-extended.0 | 2019-10-25 13:53:50.991 | error | at adapter.getStates (/opt/iobroker/node_modules/iobroker.nuki-extended/nuki-extended.js:832:34)
nuki-extended.0 | 2019-10-25 13:53:50.991 | error | at Array.forEach (<anonymous>)
nuki-extended.0 | 2019-10-25 13:53:50.991 | error | at BRIDGES.(anonymous function).callbacks.forEach.cb  (/opt/iobroker/node_modules/iobroker.nuki-extended/nuki-extended.js:841:43)
nuki-extended.0 | 2019-10-25 13:53:50.991 | error | (28447) TypeError: Cannot read property 'toString' of undefined
nuki-extended.0 | 2019-10-25 13:53:50.991 | error | (28447) uncaught exception: Cannot read property 'toString' of undefined
nuki-extended.0 | 2019-10-25 13:53:50.577 | info | (28447) Callback (with URL http://192.168.178.41:51777/nuki-api-bridge) attached to Nuki Bridge with name Wohnungstuer.
nuki-extended.0 | 2019-10-25 13:53:49.970 | info | (28447) Listening for Nuki events on port 51777.
nuki-extended.0 | 2019-10-25 13:53:49.525 | info | (28447) Polling Nuki Web API with a frequency of 15s.
nuki-extended.0 | 2019-10-25 13:53:49.437 | info | (28447) starting. Version 2.0.0 in /opt/iobroker/node_modules/iobroker.nuki-extended, node: v10.16.3

`

**Comment by AntiHeld889** [comment]
Same issuse

**Comment by Zefau** [comment]
sorry for that, v2.0.1 should fix that.

**Comment by Ilovegym66** [comment]
do you push 2.0.1 to git, please :-)

**Comment by Zefau** [comment]
done now :)
