### ISSUE TITLE
Manual configuraton will not create Bridge ID

### ISSUE THREAD

**Issue by jpawlowski** [Zefau/ioBroker.nuki-extended#36]
Using version 1.0.0, the bridge ID will not be generated or filled out when adding a new bridge using the "Add bridge" button. As this data field seems read only, there is no way to add something manually.
This is important for people to have when discovery is not working or not possible.

**Comment by jpawlowski** [comment]
I just realised that after adding the so called "optional" name, the adapter would start and fetch the bridge ID from the bridge itself.

**Comment by Zefau** [comment]
I will remove the `optional`. Thanks for the info.
