### ISSUE TITLE
Warning in log file

### ISSUE THREAD

**Issue by senger1985** [Zefau/ioBroker.nuki-extended#37]
(21345) Name, IP or API token missing for bridge ! Please go to settings and fill in IP and the API token first!

But the instance is running and connected

**Comment by Zefau** [comment]
Thanks for the valuable feedback. I can confirm this behavior.

Could you please try and install the current Github Version `v2.0.2`?
Thanks!

**Comment by Zefau** [comment]
Looks good. I guess then you have not defined a name in the adapter settings (which is required now) ?

**Comment by senger1985** [comment]
Ups, sorry.
Now the Adapter is running.
But the lockState of the lock is not available for a couple of versions

**Comment by Zefau** [comment]
Thanks for you feedback. Please see my comment in the issue #30.
