### ISSUE TITLE
Bridge API: Bell Ring of Nuki Opener

### ISSUE THREAD

**Issue by ooooli** [Zefau/ioBroker.nuki-extended#40]
Currently, the states are only reflecting the Lock functions.
e.g. ringing (state #224), recognized by the Opener is not announced.
 "224": "Ringing",

> {"id":"XXXXXXXXXXXX","smartlockId":XXXXXXXXXX,"deviceType":2,"name":"","action":224,"trigger":0,"state":0,"autoUnlock":false,"date":"2019-12-22T15:00:36.000Z","openerLog":{"activeCm":false,"activeRto":false,"source":0,"flagGeoFence":false,"flagForce":false,"flagDoorbellSuppression":false}}

**Comment by Zefau** [comment]
I will have a look at this shortly. Thanks for the report.

**Comment by Zefau** [comment]
What's your source regarding `state #224` being `Ringing`? The ioBroker log? Is the log entry you have provided generated by the nuki-extended adapter?

According to the API documentation (both [Bridge API](https://developer.nuki.io/page/nuki-bridge-http-api-190/4/#heading--lock-states) and [Web API](https://developer.nuki.io/page/nuki-web-api-1-2-1/3#heading--smart-lock-states)), state 224 does actually not exist.

**Comment by Zefau** [comment]
Apparently, the state is delivered with the log entries from the Nuki Opener (according to the [Web API documentation](https://api.nuki.io/#!/SmartlockLog/get)).

Though, if that state is not delivered by the Bridge API callback there is no possibility to announce this via the nuki-extended adapter.

I will open an issue at the Nuki developer forum and confirm.

**Comment by Zefau** [comment]
See https://developer.nuki.io/t/nuki-web-api-logs-delivers-state-224/4722

**Comment by Zefau** [comment]
@ooooli please sign up in the Nuki developer forum and vote for the related feature request, see https://developer.nuki.io/t/nuki-bridge-api-bell-ring-of-nuki-opener-as-trigger-for-callbacks/2557

The ringing event is not delivered by Nuki as of now and that feature request asks for its implementation.

**Comment by ooooli** [comment]
> @ooooli please sign up in the Nuki developer forum and vote for the related feature request, see https://developer.nuki.io/t/nuki-bridge-api-bell-ring-of-nuki-opener-as-trigger-for-callbacks/2557
> 
> The ringing event is not delivered by Nuki as of now and that feature request asks for its implementation.

Done, thanks for following up

**Comment by nachtschatt3n** [comment]
do we have ideas without the API supporting it?

**Comment by Zefau** [comment]
How is that supposed to work? Any information is being retrieved from the Bridge or Web API.

**Comment by nachtschatt3n** [comment]
well right, my ideas so far : 
- web scrape it from the nuki website (15-sec polling) (they should feel the pain) 
- try to catch the request going to the nuki servers via proxy (let's hope they are not doing SSL pinning) 
- catch the notification on the app (android is probably easier) 
- an Arduino with a microphone listening for the doorbell ?! calling iobroker URLs ?!

**Comment by ooooli** [comment]
Nuki added a new state "ringactionState" into theit beta firmware:
https://developer.nuki.io/t/bridge-beta-fw-2-7-0-1-17-0/6792
If this is accessible via adapter, the issue may be solved. I have installed the beta on my Nuki Bridge and Opener and available for testing the functionality.

**Comment by Zefau** [comment]
My bridge is currently sent in for maintenance. Could you screenshot the states without description? I will add them then. Thanks

**Comment by Zefau** [comment]
@ooooli Do you own a lock as well and could verify, if the door sensor (see https://github.com/Zefau/ioBroker.nuki-extended/issues/71) is working correctly with the fw 1.6 / 1.7 as well?

**Comment by ooooli** [comment]
> My bridge is currently sent in for maintenance. Could you screenshot the states without description? I will add them then. Thanks
Sure. The new states are created as following:
<img width="1016" alt="Bildschirmfoto 2020-08-10 um 15 32 50" src="https://user-images.githubusercontent.com/41828257/89788059-d35fe380-db1e-11ea-9332-077d620e4ad4.png">

**Comment by ooooli** [comment]
> @ooooli Do you own a lock as well and could verify, if the door sensor (see #71) is working correctly with the fw 1.6 / 1.7 as well?

Unfortunately, I don't have a lock. Only the bridge & Opener setup.

**Comment by Zefau** [comment]
@ooooli @nachtschatt3n with the latest adapter version 2.3.0 (from Github) the states `state.ringState` and `state.ringStateUpdate` should be available and reflect the bell ring. Could you please test and verify?

**Comment by nachtschatt3n** [comment]
@Zefau sure I can check it tomorrow but don't I need the beta firmware for this?

**Comment by ooooli** [comment]
> @ooooli @nachtschatt3n with the latest adapter version 2.3.0 (from Github) the states `state.ringState` and `state.ringStateUpdate` should be available and reflect the bell ring. Could you please test and verify?

The states are now named correctly:
<img width="423" alt="Bildschirmfoto 2020-08-11 um 08 00 10" src="https://user-images.githubusercontent.com/41828257/89863002-65acc980-dba9-11ea-87df-bd4226c1eb16.png">

Cross fingers, that Nuki soon adds this to the standard firmware.

**Comment by Zefau** [comment]
> @Zefau sure I can check it tomorrow but don't I need the beta firmware for this? 

@nachtschatt3n You do. It's only possible with the beta firmware for now.
