### ISSUE TITLE
Warning in Log

### ISSUE THREAD

**Issue by senger1985** [Zefau/ioBroker.nuki-extended#52]
When I start the adapter v2.1.0 (2019-02-03), this warning is displayed in the log

nuki-extended.0 | 2020-02-10 21:24:12.264 | warn | (32326) Callback not attached due to error. See debug log for details.
-- | -- | -- | --

**Comment by Zefau** [comment]
If you change the instance to `debug`, what is the log additionally saying then?

**Comment by senger1985** [comment]
I sent you an email

**Comment by Zefau** [comment]
Please install current version v2.2.0 from Github. This will NOT fix the problem, but give more details in the debug log to narrow it down.

**Comment by senger1985** [comment]
I have now loaded the new version and the adapter on "debug".

However, only the following is displayed:
"Callback not attached due to error. See debug log for details."

And the general expenses that came before.

**Comment by Zefau** [comment]
The debug log you provided by e-mail states:
```
2020-02-10 21:36:07.533 - warn:   nuki-extended.0 (13823) Callback not attached due to error. See debug log for details.
2020-02-10 21:36:07.534 - debug:   nuki-extended.0 (13823)
```

Is the second log-entry right after `warn` (with type `debug`) still empty in your log?

**Comment by senger1985** [comment]
2020-02-12 22:04:55.578 - warn: nuki-extended.0 (28941) Callback not attached due to error. See debug log for details.
--
2020-02-12 22:04:55.644 - debug: nuki-extended.0 (28941) getWebApi(): etc...

**Comment by senger1985** [comment]
Don't ask me why, but now i have no more bugs

**Comment by Zefau** [comment]
Glad to hear. Haven't had any clue what the error could possibly be ;-)
