### ISSUE TITLE
Lock States get no Updates

### ISSUE THREAD

**Issue by Wiggins2610** [Zefau/ioBroker.nuki-extended#58]
Installed the adapter, added Bridge API and WEB API Keys correctly. 
Tried it with new Tokens, too. As well as re-installing the adapter etc. 

Adapter is working, green
ACTION Buttons also work

BUT the lock states don't get an update info. The time stamp of "LastStateUpdate" doesn't change nor the lock state itself.

Any ideas what I'm doing wrong? 
  
That's what the debug log says: 

nuki-extended.1 | 2020-03-03 20:23:57.655 | warn | (11648) Callback not attached due to error. See debug log for details.
-- | -- | -- | --
nuki-extended.1 | 2020-03-03 20:23:57.381 | info | (11648) Listening for Nuki events on port 51989.
nuki-extended.1 | 2020-03-03 20:23:57.379 | info | (11648) Polling Nuki Web API deactivated.
nuki-extended.1 | 2020-03-03 20:23:56.327 | info | (11648) starting. Version 2.2.0 in /opt/iobroker/node_modules/iobroker.nuki-extended, node: v10.19.0

nuki-extended.1 | 2020-03-03 20:06:42.694 | info | (20061) Successfully triggered action -UNLOCK- on Nuki Smartlock Daheim (via Bridge API).
-- | -- | -- | --
nuki-extended.1 | 2020-03-03 20:06:34.826 | warn | (20061) Error triggering action on the Nuki device: No Nuki Hex ID given!
nuki-extended.1 | 2020-03-03 20:06:34.825 | info | (20061) Trigger action -UNLOCK- on Nuki Smartlock Daheim (via Bridge API).
nuki-extended.1 | 2020-03-03 20:04:08.283 | info | (20061) Successfully triggered action -LOCK- on Nuki Smartlock Daheim (via Bridge API).
nuki-extended.1 | 2020-03-03 20:03:56.488 | warn | (20061) Error triggering action on the Nuki device: No Nuki Hex ID given!
nuki-extended.1 | 2020-03-03 20:03:56.485 | info | (20061) Trigger action -LOCK- on Nuki Smartlock Daheim (via Bridge API).
nuki-extended.1 | 2020-03-03 20:03:56.224 | info | (20061) Successfully triggered action -UNLOCK- on Nuki Smartlock Daheim (via Bridge API).
nuki-extended.1 | 2020-03-03 20:03:47.765 | warn | (20061) Error triggering action on the Nuki device: No Nuki Hex ID given!
nuki-extended.1 | 2020-03-03 20:03:47.762 | info | (20061) Trigger action -UNLOCK- on Nuki Smartlock Daheim (via Bridge API).
nuki-extended.1 | 2020-03-03 20:02:52.695 | warn | (20061) Callback not attached due to error. See debug log for details.
nuki-extended.1 | 2020-03-03 20:02:52.429 | info | (20061) Listening for Nuki events on port 51989.
nuki-extended.1 | 2020-03-03 20:02:52.427 | info | (20061) Polling Nuki Web API deactivated.
nuki-extended.1 | 2020-03-03 20:02:50.696 | info | (20061) starting. Version 2.2.0 in /opt/iobroker/node_modules/iobroker.nuki-extended, node: v10.19.0

**Comment by Zefau** [comment]
Callback was not successfully set (`Callback not attached due to error. See debug log for details.`), which is why the adapter won't receive updates.

Please set the instance to `debug` and provide the extended log to investigate on the error message.

**Comment by Zefau** [comment]
though, `2020-03-03 20:23:57.381 | info | (11648) Listening for Nuki events on port 51989.` looks good

**Comment by Zefau** [comment]
Why are you running two instances of the adapter? If you have multiple devices, you should add them in one instance. I think the updates are not working, because the listener can only be attached once per port.
If you want to have two instances, you have to change the port on the second instance from `51989` to something else.

**Comment by Wiggins2610** [comment]
I think I troubleshooted too much. One thing was, that I added a new instance.1 and deleted the .0
For now:  
I deleted the whole adapter, gave IoBroker a reboot, installed everything new, only one instance and so on. Problem remains - Log still says: 

nuki-extended.0 | 2020-03-04 07:30:04.954 | warn | (6360) Callback not attached due to error. See debug log for details.
-- | -- | -- | --
nuki-extended.0 | 2020-03-04 07:30:04.488 | info | (6360) Listening for Nuki events on port 51989.
nuki-extended.0 | 2020-03-04 07:30:04.487 | info | (6360) Polling Nuki Web API deactivated.

**Comment by Zefau** [comment]
Please change instance to debug for more details in the log.

**Comment by Wiggins2610** [comment]
OK, I did so. What shall I provide to you?

**Comment by Wiggins2610** [comment]
Ich glaub ich hab den Fehler identifiziert und konnte es lösen: 

Ich hatte noch alte Callback IDs von meiner früheren Installation drin. Rausgefunden hab ich das im Browser mit der URL: 
http://<ip der Nuki bridge>:8080/callback/list?token=<Token der Bridge>

Dann hab ich alle IDs entfernt mit: 
http://<ip der Nuki bridge>:8080/callback/remove?id=<Nummer>&token=<Token der Bridge>

Dann hab ich den Nuki Extended Adapter neu gestartet

Unter "Konfiguration Nuki Bridge" habe ich die IP eingetragen meines iobroker Hosts. Der läuft als Debian 10-VM auf einem Intel NUC unter/auf Proxmox. Wenn ich da nichts eintrage, taucht die Callback URL nicht auf (siehe oben mit dem List Befehl)

Einzig im LOG jetzt noch auftretender Fehler/Warnung ist, aber der hat damit wohl nichts zu tun? 

nuki-extended.0 | 2020-03-04 14:52:42.942 | warn | (12005) Error triggering action on the Nuki device: No Nuki Hex ID given!
-- | -- | -- | --

Issue kann aus meiner Sicht damit geschlossen werden. ;-) Danke und Grüße nach Hamburg

**Comment by Zefau** [comment]
Alles klar, danke für die Info. Dann werde ich den Fehler im Log konkretisieren, wenn das Callback-Limit erreicht wurde. Den anderen Fehler kenne ich und bin noch am Nachforschen, woran es liegt ;-)
