### ISSUE TITLE
datum falsch bei releaseversion?

### ISSUE THREAD

**Issue by maestroat** [Zefau/ioBroker.nuki-extended#60]
hi,
kann es sein das du fehler gemach hast mit dem datum
v2.2.2 (2019-03-04)  wenn ich die history ansehe ist das sicher 2020-03-04 oder?

wollte nämlich sehen welchen von den 2 nuki adapter im iobroker ich nutze.

lg

**Comment by Zefau** [comment]
Jo, gilt für alle Releases dieses Jahr. Danke für den Hinweis, werde das gleich korrigieren.
