### ISSUE TITLE
Nuki Widgets

### ISSUE THREAD

**Issue by ramizh** [Zefau/ioBroker.nuki-extended#67]
Are there available widgets?

Any guide on how to make my own Nuki widgets?

Thank you!

**Comment by Zefau** [comment]
What do you mean by Widget?

**Comment by ramizh** [comment]
Vis Widget, such as the one for Xiaomi.

Looking for something that can show me the state of the door and make me control it with the available actions.

It could be something already there but I dont know how to do :)

**Comment by Zefau** [comment]
I'm not using vis myself. Probably best you ask in the ioBroker forum about this.

**Comment by Zefau** [comment]
I'm closing this since it is not a direct Feature Request or Bug of the adapter.

Please let me know if anything can be implemented to support Nuki Widgets for ioBroker.vis.
