### ISSUE TITLE
Nuki Opener - es hat geklingelt

### ISSUE THREAD

**Issue by Newpicsel** [Zefau/ioBroker.nuki-extended#69]
Moin,

Es gibt zumindest in der App nun die Möglichkeit, sich unter Benachrichtigungen über NUKI Web, benachrichtigen zu lassen wenn es an der Tür geklingelt hat!
Funktioniert auch wunderbar 🤗

Ist es eventuell nun möglich diese Information auch in ioBroker einzubinden?
Das wäre wirklich sehr hilfreich.

Schöne Grüße

**Comment by Hellechinno182** [comment]
Guten Morgen, daran wäre ich auch sehr interessant :)

Grüße

**Comment by Zefau** [comment]
This is a duplicated issue to https://github.com/Zefau/ioBroker.nuki-extended/issues/40.
There is no possibility to add this feature from the Nuki API unfortunately.

Please vote at Nuki Developer forum to get this added, see https://developer.nuki.io/t/nuki-bridge-api-bell-ring-of-nuki-opener-as-trigger-for-callbacks/2557.
