### ISSUE TITLE
Bridge API: Door Sensor of Nuki Lock

### ISSUE THREAD

**Issue by grojaben** [Zefau/ioBroker.nuki-extended#71]
Gibt es eine Möglichkeit bzw. einen Wert der mir den Zustand des Türsensors anzeigt? Ich würde gerne wissen, ob die Tür wirklich geschlossen ist oder ob nur der Riegel ausgefahren wurde.

**Comment by Zefau** [comment]
Tatsächlich ist es so, dass es eine sehr aktuelle Entwicklung seitens Nuki gibt, dass das bereitgestellt wird (was bisher nicht so war). Siehe https://developer.nuki.io/t/create-callback-for-door-sensor-status-in-bridge-api/1360/16?u=zefau.
Scheinbar wurde es mit `Bridge Beta FW 2.6.0 / 1.16.0 with door sensor state` eingeführt. Ich schaue es mir mal an.

**Comment by grojaben** [comment]
Vielen Dank für die schnelle Antwort und das Engagement 👍👍👍

**Comment by Dragon0501** [comment]
Guten Abend!
Ich habe einen door State gefunden dieser wird nur leider nicht aktualisiert. gibt es Fortschritte in der Richtung?

**Comment by Zefau** [comment]
Wenn du die Bridge beta firmware 2.6.0 hast, dann kommt der State mittels Callback. Ansonsten über die Web API mit geringer Polling-Frequenz via Adapter-Einstellungen.

**Comment by Dragon0501** [comment]
Habe eine Software Bridge auf dem Android Phone. Web api ist eingerichtet wo kann ich die polling frequenz einstellen?

**Comment by Dragon0501** [comment]
Einstellung gefunden. Was ist denn da so praktikabel? Ist alle zehn Sekunden zu viel?

**Comment by Zefau** [comment]
Alle 10 Sekunden sollte noch passen.

**Comment by Dragon0501** [comment]
Werde ich heut Abend versuchen. Vielen Dank!

**Comment by Dragon0501** [comment]
Funktioniert, leider so nicht nutzbar. wenn man die tür schnell öffnet und wieder schließt gibt es keine statusänderung. Schade, also als Türkontakt im herkömmlichen sinne nicht zu gebrauchen. Mal warten ob das ganze auch iwann über die softwarebridge kommt.

**Comment by Zefau** [comment]
@Dragon0501 @grojaben mit der Bridge Firmware 2.6.0 / 1.16.0 und der Adapter-Version 2.3.0 sind nun die States `state.doorState` bzw. `state.doorStateName` verfügbar (die über die Bridge API bzw. dem Callback aktualisiert werden). Könntet ihr das bitte testen?

**Comment by Dragon0501** [comment]
Gilt das auch für die Software Bridge?

**Comment by Zefau** [comment]
> Gilt das auch für die Software Bridge?

Ich musste selbst von der Software auf die Hardware Bridge wechseln, weil Nuki die Software Bridge nur schlecht supported (bzw. gar nicht).

Der Adapter kann es. Ob die Firmware seitens Nuki auch für die Software Bridge kommt weiß ich nicht, aber ich bezweifle es.

**Comment by Dragon0501** [comment]
Hardwarebridge bestellt. Lediglich die Einrichtung macht Probleme. Versuche es einzurichten, aber leider bekomme ich die Daten der Bridge nicht....

**Comment by Zefau** [comment]
> Hardwarebridge bestellt. Lediglich die Einrichtung macht Probleme. Versuche es einzurichten, aber leider bekomme ich die Daten der Bridge nicht....

Hast du die API auf der Bridge aktiviert?

**Comment by Dragon0501** [comment]
Die Bridge ist eingerichtet.

**Comment by Dragon0501** [comment]
Wie bekomme ich denn ein Update auf der Bridge angestoßen? Softwarestand ist 2.4.1. WIe bekomme ich ein update?

**Comment by Zefau** [comment]
Also du kannst die Bridge IP via Browser aufrufen und bekommst den Datensatz normal angezeigt? Welchen Fehler erhältst du denn im ioBroker Log?

**Comment by Dragon0501** [comment]
Ich weis nicht was du meinst. Der Adapter funktioniert. lediglich das mit dem Türsensor funktioniert nicht. aber das denke ich liegt an der firmwareversion

**Comment by Dragon0501** [comment]
Wenn ich den auth befehl nutze bekomme ich es angezeigt. aber eine webseite zur verwaltung unter der ip der bridge bekomme ich nicht. er sagt bad http request. Wie lautet denn der link um welchen datensatz angezeigt zu bekommen?

**Comment by Zefau** [comment]
> Lediglich die Einrichtung macht Probleme. Versuche es einzurichten, aber leider bekomme ich die Daten der Bridge nicht....

Hatte sich so gelesen, als ob die Bridge grundsätzlich nicht geht.

Du musst dich für die beta Firmware anmelden beim Nuki Support.

Die Version sollte dann in ioBroker stehen.

**Comment by Zefau** [comment]
> Wenn ich den auth befehl nutze bekomme ich es angezeigt. aber eine webseite zur verwaltung unter der ip der bridge bekomme ich nicht. er sagt bad http request. Wie lautet denn der link um welchen datensatz angezeigt zu bekommen?

Das ist `/list` siehe auch https://developer.nuki.io/page/nuki-bridge-http-api-1-11/4#heading--list

**Comment by Dragon0501** [comment]
Der BooleanDoorState (closed) wird leider nicht aktualisiert.
DoorStateName und Doorstate wird aktualisiert. dauert aber zwischen 2 und 5 sekunden.

**Comment by Zefau** [comment]
`BooleanDoorState` ? Es sollten nur zwei neue State dazu gekommen sein: `DoorStateName` und `DoorState`. Lösch bitte den Datenpunkt, der sich nicht aktualisiert und starte den Adapter neu. Erscheint dieser dann wieder?

**Comment by Dragon0501** [comment]
Problem gelöst! Vielen Dank!
