### ISSUE TITLE
unlock öffnet Tür, statt "nur" aufzuschließen

### ISSUE THREAD

**Issue by truegreyhound** [Zefau/ioBroker.nuki-extended#79]
Ich habe mir ein kleines Skript geschrieben, dass in Abhängigkeit der Anwesenheit die Tür Abends zuschließt (lock) und morgens aufschließt. Nun musste ich feststellen, das "unlock" eigentlich ein "unlatch" ist. Das heißt, die Haustür war morgens entriegelt, was natürlich nicht Sinn der Sache ist.
Wozu gibt es unlock und unlatch, wenn sie das gleich auslösen?
Ich nutze Nuki (erste Version) mit der Bridge ohne Webanbindung.

**Comment by Zefau** [comment]
Welche Adapter-Version?
Was passiert, wenn du direkt den Datenpunkt `nuki-extended.0.smartlocks.wohnungstür._ACTION` bzw. die Datenpunkte darin triggerst?
Was steht im Log, wenn du auf `debug` stellst?

**Comment by truegreyhound** [comment]
`nuki-extended.0	2020-07-28 19:56:31.371	debug	(24275) Updating device smartlocks.sll1 with payload: {"nukiId":91049449,"state":{"deviceType":0,"mode":2,"state":3,"batteryCritical":false,"timestamp":"2020-07-28T17:56:31+00:00","locked":3,"lastStat
nuki-extended.0	2020-07-28 19:56:31.368	debug	(24275) Received payload via callback: {"nukiId":91049449,"state":{"deviceType":0,"mode":2,"state":3,"stateName":"unlocked","batteryCritical":false,"timestamp":"2020-07-28T17:56:31+00:00"}}
nuki-extended.0	2020-07-28 19:56:26.707	info	(24275) Successfully triggered action -UNLOCK- on Nuki Smartlock SLL1 (via Bridge API).`

**Comment by truegreyhound** [comment]
Adapter-Version: 2.2.6

**Comment by Zefau** [comment]
Also laut Log wird `unlock` korrekt mit `state` `3` verarbeitet. Kommt auch vom Callback (also von der Bridge) so zurück.
Erscheint mir kein Fehler beim Adapter zu sein.

Wenn du normal mit der Nuki App unlockst, geht die Tür dann nicht auf? Kannst du das mal probieren, ob das ggf. dasselbe Verhalten ist?

Sofern das wie gewünscht klappen sollten, dann bitte mal direkt die API über den Browser triggern.
Dazu die folgende URL (mit deinem Parametern) einfach im Browser öffnen:
```
http://<bridgeIp>:8080/lockAction?token=<token>&nukiId=<nukiId>&action=1
```
zum Beispiel
```
http://192.168.178.40:8080/lockAction?token=1Xtgbi$&nukiId=346978779&action=1
```

**Comment by truegreyhound** [comment]
unlock und unlatch bewirken bei mir immer das öffnen der Tür, egal ob per Handy oder per URL.

Habe dazu inzwischen ein Mail an den Nuki-Support geschrieben. 
Außerdem erkennt Nuki nicht den Status des Schlosses nach einer manuellen Schließung, was die gesamte Logik zerstört.
Erkennt dein Nuki den Status, nachdem manuell geschlossen/geöffnet wurde?

Denke, dass kann hier geschlossen werden.
