### ISSUE TITLE
too many callbacks 

### ISSUE THREAD

**Issue by arteck** [Zefau/ioBroker.nuki-extended#80]
![grafik](https://user-images.githubusercontent.com/6681528/88671595-c686cd00-d0e6-11ea-91c4-06ca6ca23223.png)

sry but .. the delete button does not work .. no log info .. also not in debug mode.. after press the button

![grafik](https://user-images.githubusercontent.com/6681528/88672417-bae7d600-d0e7-11ea-86a4-96c99c822c5a.png)

you have a bug in admin.. this is a message after press the delete button

**Comment by Zefau** [comment]
Could you try 2.2.7 from Github ?

**Comment by arteck** [comment]
ahhhh... thx
