### ISSUE TITLE
Web Adapter Update - Web View is broken

### ISSUE THREAD

**Issue by Grothesk242** [Zefau/ioBroker.nuki-extended#88]
After the most recent upgrade to web adapter 3.0.12 the web view doesn't load the data from the Nuki web api.

**Comment by salopette** [comment]
Is there a solution? Web still doesn't work.

**Comment by Zefau** [comment]
Please try v2.3.0 from Github. This should address and fix this.

**Comment by salopette** [comment]
![sshot-2](https://user-images.githubusercontent.com/32480002/91345545-d544ca80-e7df-11ea-9163-d336e49009c3.jpg)


How do I do that? with only 2.2.6 is displayed as the last current one

**Comment by Zefau** [comment]
Via the cat. Please google how to install from Github.

**Comment by salopette** [comment]
it works! THX!
